### ISSUE TITLE
Infrastructure deletion when no network was created

### ISSUE THREAD

**Issue by lotharbach** [23technologies/gardener-extension-provider-hcloud#20]
**How to categorize this issue?**

/area networking
/kind bug

**What happened**:
Network was not created due to quota. Now Infrastructure can't be deleted and the controller crashes:

```
{"level":"info","ts":"2022-11-09T13:00:13.793Z","msg":"Deleting the Infrastructure","controller":"infrastructure","object":{"name":"23ke-run-237c","namespace":"shoot--23ke-ci--23ke-run-237c"},"namespace":"shoot--23ke-ci--23ke-run-237c","name":"23ke-run-237c","reconcileID":"020a3111-b5a7-4676-a0dc-5538ae90ee50",
"operation":"delete"}                                                                                                                                       E1109 13:00:13.808850       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 708 [running]:                                                                                                                                    k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1d16760?, 0x33d60b0})                                                                                          /go/src/github.com/23technologies/gardener-extension-provider-hcloud/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()                                                                          /go/src/github.com/23technologies/gardener-extension-provider-hcloud/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:110 +0xb9
panic({0x1d16760, 0x33d60b0})                                                                                                                                   /usr/local/go/src/runtime/panic.go:838 +0x207                                                                                                           github.com/23technologies/gardener-extension-provider-hcloud/pkg/controller/infrastructure/ensurer.EnsureNetworksDeleted({0x2312560?, 0xc00b0e0000?}, 0xc00b
0e0000?, {0xc008791ee0?, 0x6?}, 0x2022684?)                                                                                                                     /go/src/github.com/23technologies/gardener-extension-provider-hcloud/pkg/controller/infrastructure/ensurer/networks.go:113 +0x27                        github.com/23technologies/gardener-extension-provider-hcloud/pkg/controller/infrastructure.(*actuator).delete(0xc00ad56e10?, {0x2312560, 0xc00b0e0000}, 0xc0
05c923c0, 0x0?)                                                                                                                                                 /go/src/github.com/23technologies/gardener-extension-provider-hcloud/pkg/controller/infrastructure/actuator_delete.go:52 +0xcf                          github.com/23technologies/gardener-extension-provider-hcloud/pkg/controller/infrastructure.(*actuator).Delete(0x2005207?, {0x2312560?, 0xc00b0e0000?}, {{0x1
b?, 0x2313738?}, 0x2312560?}, 0xc00b0e0000?, 0x23145f0?)                                                                                                        /go/src/github.com/23technologies/gardener-extension-provider-hcloud/pkg/controller/infrastructure/actuator.go:95 +0x29                                 github.com/gardener/gardener/extensions/pkg/controller/infrastructure.(*reconciler).delete(0xc0003f0550, {0x2312560, 0xc00b0e0000}, {{0x23145f0?, 0xc00ad56e10?}, 0xc00051cb40?}, 0xc005c923c0, 0x1d?)                                                                                                                      /go/src/github.com/23technologies/gardener-extension-provider-hcloud/vendor/github.com/gardener/gardener/extensions/pkg/controller/infrastructure/reconc
iler.go:192 +0x209                                                                                                                                          github.com/gardener/gardener/extensions/pkg/controller/infrastructure.(*reconciler).Reconcile(0xc0003f0550, {0x2312608, 0xc00ad56690}, {{{0xc0057445c0?, 0x2312608?}, {0xc00573f400?, 0xc0057445c0?}}})                                                                                                                     /go/src/github.com/23technologies/gardener-extension-provider-hcloud/vendor/github.com/gardener/gardener/extensions/pkg/controller/infrastructure/reconciler.go:127 +0x1225
github.com/gardener/gardener/pkg/controllerutils/reconciler.(*operationAnnotationWrapper).Reconcile(0xc0007457a0, {0x2312608, 0xc00ad56690}, {{{0xc0057445c0?, 0x10?}, {0xc00573f400?, 0x40d7e7?}}})                                                                                                                        /go/src/github.com/23technologies/gardener-extension-provider-hcloud/vendor/github.com/gardener/gardener/pkg/controllerutils/reconciler/operation_annotation_wrapper.go:73 +0xa38
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x2312560?, {0x2312608?, 0xc00ad56690?}, {{{0xc0057445c0?, 0x1ee6760?}, {0xc00573f400?, 0x4041f4?}}})                                                                                                                                        /go/src/github.com/23technologies/gardener-extension-provider-hcloud/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001a55e0, {0x2312560, 0xc000f01d80}, {0x1db5520?, 0xc008fcf380?})
    /go/src/github.com/23technologies/gardener-extension-provider-hcloud/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:320 +0x33c                                                                                                                                                         sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001a55e0, {0x2312560, 0xc000f01d80})                               /go/src/github.com/23technologies/gardener-extension-provider-hcloud/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()                                                                            /go/src/github.com/23technologies/gardener-extension-provider-hcloud/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:234 +0x85                                                                                                                                                          created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2                                                                     /go/src/github.com/23technologies/gardener-extension-provider-hcloud/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:230 +0x
325
```
**What you expected to happen**:
The Infrastructure to be deleted when not network exists.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
Okeanos 23ke-ci/23ke-run-237c

**Comment by j2L4e** [comment]
closed via #117
